site_name: SkyWay JS SDK APIリファレンス
pages:
    - Introduction: index.md
    - Peer: peer.md
    - MediaConnection: mediaconnection.md
    - DataConnection: dataconnection.md
    - MeshRoom: meshroom.md
    - SFURoom: sfuroom.md
theme:
  name: 'material'
  language: 'ja'
extra:
  search:
    language: 'jp'